version: '3.8'

services:
  translation-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: japanese-railway-translation-api
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - HF_HOME=/home/app/.cache/huggingface
    volumes:
      - ./train_entity.csv:/app/train_entity.csv:ro
      - huggingface_cache:/home/app/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  huggingface_cache:
